# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Beer Batter Breakfast
description:      'A blog about beer pancakes.'
url:              http://localhost:4000
baseurl:          '/'
paginate:         5

author:
  name:           'Brad Orego'
  url:            http://bradorego.com

# Custom vars
version:          1.0.0

# stupid github pages doesn't allow sass :(
# sass:
#   sass_dir: public/css
#   style: :compressed
