# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Beer Batter Breakfast
description:      'A blog about beer pancakes.'
url:              http://borego.github.io/beerbatterbreakfast.github.io/
baseurl:          'http://borego.github.io/beerbatterbreakfast.github.io/'
paginate:         5

author:
  name:           'Brad Orego'
  url:            http://bradorego.com

# Custom vars
version:          1.0.0
