# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Beer Batter Breakfast
description:      'A blog about beer pancakes.'
url:              http://beerbatterbreakfast.com
baseurl:          'http://beerbatterbreakfast.com'
paginate:         5

author:
  name:           'Brad Orego'
  url:            http://bradorego.com

# Custom vars
version:          1.0.0

sass:
  sass_dir: public/css
  style: :compressed
