# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            Beer Batter Breakfast
description:      'A blog about beer pancakes.'
url:              http://beerbatterbreakfast.com
baseurl:          '/'
paginate:         5

author:
  name:           'Brad Orego'
  url:            http://bradorego.com

# Custom vars
version:          1.0.0

authors:
  bradorego:
    name: Brad
    gravatar: 5abc28e6bc87799335d8ccaad3662e53
    twitter: bradorego
    website: http://bradorego.com

# stupid github pages doesn't allow sass :(
# sass:
#   sass_dir: public/css
#   style: :compressed

# RSS?
name: Beer Batter Breakfast
